sudo: false
dist: trusty
language: php
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 8.0

before_script:
  - composer install
  - composer require nyholm/psr7

script:
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - composer test
