sudo: false
dist: trusty
language: php
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
before_script:
  - composer install
  - composer require nyholm/psr7
